name: Develop - Prerelease

on:
  push:
    branches: [develop]

jobs:
  prerelease:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v3
        with:
          versionSpec: '6.x'

      - name: Calculate version
        uses: gittools/actions/gitversion/execute@v3
        id: gitversion

      - name: Log calculated version
        run: echo "GitVersion calculated version ${{ steps.gitversion.outputs.SemVer }}"

      - name: Restore dependencies
        run: dotnet restore
        working-directory: ./src

      - name: Build solution
        run: dotnet build -c Release --no-restore
        working-directory: ./src

      - name: Run tests
        run: dotnet test -c Release --no-build --no-restore --verbosity normal
        working-directory: ./src

      - name: Pack NuGet packages (testing only)
        run: dotnet pack -c Release --no-restore -o ../artifacts
        working-directory: ./src

      - name: Upload artifacts for testing
        uses: actions/upload-artifact@v4
        with:
          name: prerelease-packages-${{ steps.gitversion.outputs.SemVer }}
          path: artifacts
          retention-days: 7