name: Develop - NuGet Prerelease

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish-prerelease:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: '1'
      DOTNET_CLI_TELEMETRY_OPTOUT: '1'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Build (versioning via GitVersion.MsBuild)
        run: |
          dotnet restore ./Cocoar.Capabilities.slnx
          dotnet build -c Release ./Cocoar.Capabilities.slnx
        working-directory: ./src

      - name: Restore dependencies
        run: dotnet restore ./Cocoar.Capabilities.slnx
        working-directory: ./src

      - name: Build solution
        run: dotnet build ./Cocoar.Capabilities.slnx -c Release --no-restore
        working-directory: ./src

      - name: Run tests
        run: dotnet test ./Cocoar.Capabilities.slnx -c Release --no-build --no-restore --verbosity normal
        working-directory: ./src

      - name: Pack NuGet packages (incl. symbols)
        run: >
          dotnet pack ./Cocoar.Capabilities/Cocoar.Capabilities.csproj -c Release --no-restore
          /p:IncludeSymbols=true /p:SymbolPackageFormat=snupkg
          -o ../artifacts
        working-directory: ./src

      - name: Ensure packages exist
        run: |
          shopt -s nullglob
          files=(artifacts/*.nupkg artifacts/*.snupkg)
          (( ${#files[@]} )) || { echo "::error ::No packages found in artifacts/"; exit 1; }

      - name: Upload artifacts (audit)
        uses: actions/upload-artifact@v4
        with:
          name: prerelease-packages
          path: artifacts
          retention-days: 30

      - name: Push prerelease to NuGet.org
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: |
          shopt -s nullglob
          for p in artifacts/*.nupkg artifacts/*.snupkg; do
            echo "Pushing prerelease package: $p"
            dotnet nuget push "$p" --source https://api.nuget.org/v3/index.json --api-key "$NUGET_API_KEY" --skip-duplicate
          done