name: Develop - Prerelease

on:
  push:
    branches: [ develop ]

jobs:
  prerelease:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Debug git state
        run: |
          git rev-parse --is-shallow-repository
          git tag --list --sort=-creatordate | head -n 10
          git describe --tags --always --long || true
          
      - name: GitVersion
        uses: GitTools/actions/gitversion/execute@v3
        with:
          useConfigFile: true
          additionalArguments: '/diag'
        id: gv
      
      - name: Log calculated version
        run: echo "GitVersion calculated version ${{ steps.gv.outputs.SemVer }}"

      - name: Setup .NET (8 + 9)
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
            9.0.x

      - name: Restore dependencies
        run: dotnet restore
        working-directory: ./src

      - name: Build solution
        run: dotnet build -c Release --no-restore -p:Version=${{ steps.gv.outputs.SemVer }} -p:AssemblyVersion=${{ steps.gv.outputs.AssemblySemVer }} -p:FileVersion=${{ steps.gv.outputs.AssemblySemFileVer }}
        working-directory: ./src

      - name: Run tests
        run: dotnet test -c Release --no-build --no-restore --verbosity normal
        working-directory: ./src

      - name: Pack NuGet packages (alpha)
        run: dotnet pack -c Release --no-restore -o ../artifacts -p:Version=${{ steps.gv.outputs.SemVer }}
        working-directory: ./src

      - name: Upload artifacts for testing
        uses: actions/upload-artifact@v4
        with:
          name: prerelease-${{ steps.gv.outputs.SemVer }}
          path: artifacts
          retention-days: 7