name: PR Validation

on:
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: GitVersion
        uses: GitTools/actions/gitversion/execute@v3
        with:
          useConfigFile: true
        id: gv

      - name: Log calculated version
        run: echo "GitVersion calculated version ${{ steps.gv.outputs.SemVer }}"

      - name: Restore dependencies
        run: dotnet restore
        working-directory: ./src

      - name: Build solution
        run: dotnet build -c Release --no-restore -p:Version=${{ steps.gv.outputs.SemVer }} -p:AssemblyVersion=${{ steps.gv.outputs.AssemblySemVer }} -p:FileVersion=${{ steps.gv.outputs.AssemblySemFileVer }}
        working-directory: ./src

      - name: Run tests
        run: dotnet test -c Release --no-build --no-restore --verbosity normal
        working-directory: ./src