name: Release - Stable

on:
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.release.id }}
  cancel-in-progress: true

jobs:
  publish:
    if: github.event.release.target_commitish == 'develop'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: '1'
      DOTNET_CLI_TELEMETRY_OPTOUT: '1'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Extract version from tag
        id: extract_version
        shell: bash
        run: |
          TAG="${{ github.event.release.tag_name }}"
          echo "Release tag: $TAG"
          if [[ ! "$TAG" =~ ^v[0-9]+\.[0-9]+\.[0-9]+(-[0-9A-Za-z\.-]+)?$ ]]; then
            echo "::error ::Tag must be like vX.Y.Z or vX.Y.Z-<pre>"); exit 1;
          fi
          SEMVER="${TAG#v}"
          echo "SemVer: $SEMVER"
          echo "semver=$SEMVER" >> "$GITHUB_OUTPUT"

      - name: Restore dependencies
        run: dotnet restore ./Cocoar.Capabilities.slnx
        working-directory: ./src

      - name: Build solution
        run: dotnet build ./Cocoar.Capabilities.slnx -c Release --no-restore
        working-directory: ./src

      - name: Run tests
        run: dotnet test ./Cocoar.Capabilities.slnx -c Release --no-build --no-restore --verbosity normal
        working-directory: ./src

      - name: Pack NuGet packages (incl. symbols)
        run: >
          dotnet pack ./Cocoar.Capabilities/Cocoar.Capabilities.csproj -c Release --no-restore
          /p:IncludeSymbols=true /p:SymbolPackageFormat=snupkg
          /p:Version=${{ steps.extract_version.outputs.semver }}
          -o ../artifacts
        working-directory: ./src

      - name: Ensure packages exist
        run: |
          shopt -s nullglob
          files=(artifacts/*.nupkg artifacts/*.snupkg)
          (( ${#files[@]} )) || { echo "::error ::No packages found in artifacts/"; exit 1; }

      - name: Upload artifacts (audit)
        uses: actions/upload-artifact@v4
        with:
          name: packages-${{ steps.extract_version.outputs.semver }}
          path: artifacts
          retention-days: 7

      - name: Push to NuGet.org
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: |
          shopt -s nullglob
          for p in artifacts/*.nupkg artifacts/*.snupkg; do
            dotnet nuget push "$p" --source https://api.nuget.org/v3/index.json --api-key "$NUGET_API_KEY" --skip-duplicate
          done